controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_controller:
      type: arcus_controllers/AckermannController

ackermann_controller:
  ros__parameters:
    drive_wheel: "arcus_rear_left_wheel_joint"
    steering_left_wheel: "arcus_front_left_steering_joint"
    steering_right_wheel: "arcus_front_right_steering_joint"
    use_dual_steering: true
    track_width: 0.16
    wheel_radius: 0.04
    wheel_base: 0.255
    max_steering_angle: 0.4
    max_speed: 1.0
    cmd_timeout: 0.5